pipeline:
  # test:
  #   image: composer
  #   commands:
  #     - cp .env.example .env
  #     - composer install
  #     - vendor/bin/phpunit
  build:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: aal89/narcos
    tags: latest
    when:
      event: push
  deploy:
    image: appleboy/drone-ssh
    host: alexapp.nl
    secrets: [ ssh_username, ssh_password ]
    port: 22
    script:
      - ((docker stop narcos && docker rm narcos) || true)
      - docker pull aal89/narcos
      - docker image prune --force
      - docker run -d -p 127.0.0.1:9797:8189 --env-file ./narcos/.env --name narcos --network mysqlnet aal89/narcos
      - docker exec narcos sh -c 'php artisan migrate'
    when:
      event: push
  report:
    image: appleboy/drone-discord
    secrets: [ discord_webhook_id, discord_webhook_token ]
    avatar_url: https://git.alexapp.nl/avatars/11
    message: Build **{{build.number}}** for **{{repo.name}}** reported **{{build.status}}**. Review {{build.event}} on {{build.branch}}? https://build.alexapp.nl/{{repo.owner}}/{{repo.name}}/{{build.number}}
    when:
      status:  [failure, success]

branches: master